.gitignore
=> ignore paths where we bring in companion repos

.gitignore, README.md
=> More ignores

core/chef/cookbooks/network/recipes/lldpd.rb
=> Update for rhel/redhat support

core/rails/app/models/deployment.rb, core/rails/app/models/event_sink.rb, core/rails/app/models/tenant.rb
also need cleanup deleted by moving nodes and deployments to root
we should also be able to generate tenant events
This work is needed so that tenants can do useful work.
=> when tenants are added, add a deployment. 

core/rails/app/controllers/network_ranges_controller.rb, core/rails/app/controllers/networks_controller.rb, core/rails/app/models/barclamp_dhcp/mgmt_service.rb, core/rails/app/models/network.rb, core/rails/app/models/network_allocation.rb, core/rails/app/models/network_range.rb, core/rails/db/migrate/20160921094500_make_ranges_specify_dhcp_parameters.rb, deploy/compose/config-dir/api/config/networks/the_admin.json.forwarder, deploy/compose/config-dir/api/config/networks/the_admin.json.mac, deploy/compose/init_files.sh, go/rebar-api/datatypes/network.go, go/rebar-dhcp/subnet.go
Do not pull yet, more coming here.
=> Allow network ranges to carry lease information

deploy/compose/config-dir/provisioner/bootenvs/ubuntu-14.04.3.json, deploy/compose/config-dir/provisioner/bootenvs/ubuntu-14.04.4.json
14.04 and 16.04 are at latest.  We may want to change that.
=> Put back 14.04.4 and 14.04.3 from raw isos.

deploy/compose/common.env, tools/build-offline.sh
Add a hack script to build offline parts.
=> Make revproxy not update from the internet by default

core/rails/app/controllers/deployments_controller.rb
everything.
Also fix issue with real nodes. structure was being overwritten each time.
=> Fix wizard when dealing with attributes.  They need to be saved after

core/barclamps/bios.yml, core/barclamps/ipmi.yml, core/barclamps/raid.yml, core/barclamps/rebar.yml, core/rails/app/models/barclamp_bios/dellrseries.rb, core/rails/app/models/barclamp_bios/discover.rb, core/rails/app/models/barclamp_bios/driver.rb, core/rails/app/models/barclamp_bios/supermicro.rb, core/rails/app/models/barclamp_ipmi/discover.rb, core/rails/app/models/barclamp_ipmi/wsman_hammer.rb, core/rails/app/models/node.rb, core/script/roles/bios-flash/01-flash.sh, core/script/roles/ipmi-flash/01-stub.sh, deploy/compose/common.env, sledgehammer/build_sledgehammer.sh
Start by stubbing out OOB BIOS paths.  This PR also adds IPMI and BIOS in-band updating along with some fixups to noderole dependencies and noderole movement.
=> Start adding firmware update stuff

core/tools/kvm-release, deploy/Vagrantfile, deploy/workloads/add-provider.sh
vagrant still a work in process, but these changes are required no matter what.
=> minor cleanups & warnings

containers/cloudwrap/cloudwrap/api.rb, core/rails/app/models/aws_provider.rb
if subnet_id is set in the create hints then it will override the provider.
=> allow node hints to override subnet

core/rails/app/controllers/capabilities_controller.rb, core/rails/app/models/capability.rb, core/rails/app/models/role.rb, core/rails/db/migrate/20160629171700_add_tenants.rb
small patch based on UX work.
The Role additions will slow the API slightly; however, this data is helpful when working with roles.
=> Expose Role properties & protect Capabilities

.gitignore, deploy/compose/init_files.sh
I'm sure there is a better way to do this, but it works for me.
=> Make sed work for MAC.

core/barclamps/test.yml, core/rails/app/controllers/attribs_controller.rb, core/rails/app/models/barclamp_rebar/jig.rb
This is setting the groundwork for more control of hardware and easier creation of roles.
=> Attrib update  /  Role Scripts in Meta Data

deploy/compose/docker-compose-common.yml
when we moved the repos, it changed the paths for debug and test file maps.
=> fix example paths for debug & dev

core/rails/app/controllers/docs_controller.rb
fix eula path.  
this does not fully correct the EULA issue with UX login, but it does help/
=> fix path for license

core/barclamps/bios.yml
When I tried to update the attribute, the schema was not allowing updates.
This change allows updates.
=> Schema requires all values to be strings

core/rails/app/models/barclamp_rebar/ansible_playbook_jig.rb
This added type of data allows the jig to create plays from metadata in the role.  This is very handy for adding Ansible roles dynamically to a running system.  Updates to the role can be made dynamically and then re-run.
Here's an example of the metadata needed, it's pretty basic.  playbook_file & playbook_path must be "." because they are required for other Ansible delivery models.
barclamp:
name: ahold
display: Ansible Holder
license: APLv2
copyright: "RackN, 2016"
roles:
- name: areference
description: 'Ansible Metadata Playbook'
jig: ansible-playbook
icon: "spellcheck"
flags:
- implicit
requires:
- rebar-installed-node
metadata:
playbook_scope: node
playbook_file: "."
playbook_src_paths:
areference: metadata
playbook_path: "."
role_role_map:
areference:
- areference
tasks:
main: …
=> allow generation of ansible plays from metadata

go/build-rebar.sh, go/classifier/main.go, go/rebar-api/datatypes/event.go
It reuses the backend parts of the rule engine to do all the heavy lifting.
=> Resurrect the standalone node classifier

core/rails/app/models/barclamp_rebar/ansible_playbook_jig.rb
while trying to make the UX for the metadata format, it quickly became obvious, that we really should just have one list of files and add more structure instead of having three areas.  That allows us to add new paths to the file types as needed (since the type if really a path).
It also makes the UX much easier to create since there's just one list of files.
=> simplify format of metadata to make it easier to edit

core/rails/app/models/attrib.rb
of deployment roles.  Also make a copy of the original structure so
that when the update function works we can actually see if the value
changes.
The poke function needs to force the node roles to block or todo.
The blocking state will wait until committed data is commited on the
deployment or node role when they are committed.  Otherwise, we
either don't change the state of the node roles or we run the
node roles with old data.
Profiles will not work correctly.  Changing profiles will not currently update the attributes.
The FLOW for updating attributes is, mark the deployment proposed,
update the attribute, commit the deployment.  This will generate the
proper running of node roles with the correct data.
=> Update the attribute update function to poke the childern of node roles

core/rails/app/models/barclamp_rebar/ansible_playbook_jig.rb
This only runs the playbook with this role.  Note the role does not need
to be the role running.  e.g. etcd-install runs on all etcd nodes only.
Add a special case for ansible_ipv4.address to be filled in to handle
the case that we don't run facts on all nodes.
Add a new field option for inventory map to inject fields from the node.
This works with the attributes and other processing system.
=> Adds a new scope for a playbook - role.

deploy/compose/config-dir/provisioner/templates/centos-6.ks.tmpl, deploy/compose/config-dir/provisioner/templates/centos-7.ks.tmpl, deploy/compose/config-dir/provisioner/templates/net-post-install.sh.tmpl
The cloud instances all seem to have python installed in them.
Make our installed OSes as well.  This allows ansible to run on these systems.
=> Make sure that python is installed to allow ansible to run correctly.

go/classifier/main.go
It helps if we actaully parse the flags and set the ruleset we are
working with as active.
=> Fix a couple of other trivial bugs in the classifier.

core/rails/app/controllers/support_controller.rb, core/rails/config/routes.rb
it's confusing to send people to the old UX for login, this will digest auth and then redirect.
=> root page should redirect to new ux after digest auth

core/barclamps/rebar.yml, core/rebar.yml, deploy/compose/config-dir/provisioner/templates/centos-6.ks.tmpl, deploy/compose/config-dir/provisioner/templates/centos-7.ks.tmpl, deploy/compose/config-dir/provisioner/templates/net-post-install.sh.tmpl
Add an ansible-client role that is added on all nodes running
the ansible playbook jig to install python appropriately.
=> Remove python from the install images (was added for ansible)

core/rails/app/controllers/nodes_controller.rb
a very hacky fix - this field is a postgresql special array type and may not be handled by the update method.
strangely, this worked from API PATCH?!
Also, changed update to use same code as other updates
=> resolve profiles not saving issue from API PUT

deploy/workloads/cluster/README.md, deploy/workloads/cluster/deploy-001.json, deploy/workloads/cluster/deploy-002.json, deploy/workloads/multideploy.sh
handy little script and templates that can be used to create (& destroy) multiple deployments.
this is still a basic thing, but very capable for a starting script.
=> script to build/destroy multiple deployments for classes, etc

core/barclamps/ipmi.yml, core/chef/cookbooks/ipmi/recipes/configure.rb
in IPMI tool.  Default to dedicated like before or string of choice
=> Change ipmi-shared to a string that can handle the 12G/13G changes

containers/cloudwrap/cloudwrap/api.rb
this does NOT include rebuilding cloudwrap!
=> update packet image to match latest choice

core/tools/kvm-slave
needed for OpenStack testing b/c 20 Gb is not enough :(
=> allow user to configure number of drives

deploy/aws-add-provider.sh
makes it easy to add a AWS provider if you already have working AWS credentials
=> use AWS credential information to add AWS provider

deploy/aws-add-provider.sh
based on testing, fix the admin-ip 
and remove requirement to download the rebar cli
=> improve aws-provider script to NOT require rebar cli

deploy/run-in-packet.sh
healthier in general
needed specifically because of Apparmour bug
=> update packet image to latest

deploy/tasks/base-centos.yml, deploy/tasks/base-debian-7.yml, deploy/tasks/base-debian-8.yml, deploy/tasks/base-ubuntu1404.yml, deploy/tasks/base-ubuntu1604.yml, deploy/tasks/compose.yml, deploy/tasks/docker-linux.yml, deploy/tasks/systemd-proxies.yml
most of deltas are handle deprecation warning for sudo
changed order of git clone because it was failing for remote install (via packet)
git clone is now required for workfload.
added copy of cache raid files
=> ansible tweaks for remote execution, sudo to become

deploy/aws-add-provider.sh
=> fix typo in aws create!

deploy/quickstart.sh, deploy/run-in-system.sh, deploy/tasks/compose.yml, deploy/workloads/cluster/deploy-001.json, deploy/workloads/cluster/deploy-002.json
Detect is we are installing on clouds and skip the ISO download
minor tweaks to wording.
=> Optimize AWS/Google Installs

deploy/aws-add-provider.sh
=> need to override endpoint if set locally

.gitignore, deploy/aws-add-provider.sh
trying to keep this script VERY simple for quick start.
=> make add-aws not require anything except curl

core/rails/app/controllers/deployments_controller.rb
this is required for classrooms creates
=> nodes need to be created in the DEPLOYMENT tenant

core/rails/app/models/barclamp_cluster/service_role.rb, core/tools/kvm-slave
Handle failure in cluster role when not all attributes are created.
=> Fix kvm-slave to create correct number of disks

core/barclamps/flash.yml, core/barclamps/raid.yml, tools/gen_role_and_attrib_docs.rb
Also add documentation stanzas to a few roles and attribs to test it out with
=> Add a doc autogeneration script for role and attrib docs.

containers/rebar-rev-proxy/Dockerfile.in, containers/rebar-rev-proxy/entrypoint.d/25-build-ux.sh, go/rebar-rev-proxy/rebar-rev-proxy.go
Removes some of the chaos that was our custom building system that is replaced with this: 
rackn/digitalrebar-ux#361
=> Added UX brunch capability

core/barclamps/bios.yml, core/barclamps/flash.yml, core/barclamps/hw-support.yml, core/barclamps/ipmi.yml, core/barclamps/raid.yml, core/chef/cookbooks/ipmi/recipes/configure.rb, core/chef/cookbooks/ipmi/recipes/discover.rb, core/chef/cookbooks/raid/recipes/install_tools.rb, core/rails/app/models/barclamp_bios/configure.rb, core/rails/app/models/barclamp_bios/discover.rb, core/rails/app/models/barclamp_flash/discover.rb, core/rails/app/models/barclamp_ipmi/amt_configure.rb, core/rails/app/models/barclamp_ipmi/amt_discover.rb, core/rails/app/models/barclamp_ipmi/amt_hammer.rb, core/rails/app/models/barclamp_ipmi/configure.rb, core/rails/app/models/barclamp_ipmi/discover.rb, core/rails/app/models/barclamp_raid/configure.rb, core/rails/app/models/barclamp_raid/discover.rb, core/rails/app/models/barclamp_raid/tools_install.rb, core/script/roles/amt-discover/01-amt-discover.sh, core/script/roles/dell-firmware-flash/01-configure-repos.sh, core/script/roles/firmware-flash/01-flash.sh
hardware specific subsystems.  Default them to off.
=> Add new role hw-support to enable/disable the various

sledgehammer/publish.sh, sledgehammer/sledgehammer.ks
The image is already in aws.  I didn't update the rest of the DR's sledgehammer usage.
=> Latest code and an example publish script
