digitalrebar/digitalrebar

core/rails/app/controllers/deployment_roles_controller.rb, core/rails/app/models/deployment_role.rb
This is needed for the UX to correctly inform users about DR state.
property is ignored on create and update
=> expose proposed state for REST model, 

go/build-rebar.sh
This allow the script to be used on custom trees.
=> Don't checkout on latest.  Assume on master.

core/barclamps/test.yml, core/rails/app/models/barclamp.rb, core/rails/app/models/barclamp_test/jig.rb, core/rails/app/models/jig.rb, core/rails/db/migrate/20160914154200_add_nodeicon.rb
This allows users and workloads to set icons for nodes.
the icon only shows up if the node is ready
=> add icon to node model and allow it to be set by flag from noop role

deploy/scripts/wait_for_rebar.sh, deploy/tasks/compose.yml
for rule-engine/rebar-api sync up.  Up the time outs.
=> Due to exponential backoff on container restarts, this can take awhile

core/rails/app/controllers/capabilities_controller.rb, core/rails/db/seeds.rb
This patch creates two new types of capabilities:
1) *_ALL groups that are made automatically from the root capabilities
2) DR_ groups that are designed for specific use cases.  These are preliminary and will be updated over the next few weeks as we tune the exact permissions.
Also, the controller had to be updated so that dr-groups could be edited.
There is a matching change in the UX to expose these groups.
=> Create capability groups (preliminary)

core/barclamps/ipmi.yml, core/chef/cookbooks/ipmi/recipes/configure.rb, core/rails/app/models/barclamp_ipmi/configure.rb, core/rails/app/models/barclamp_ipmi/discover.rb
This lets the IPMI handling code configure everything but the network
when DigitalRebar is not responsible for handling the network
configuration of the host system, and handles configuring the BMC to use
DHCP if the BMC network for the node has a DHCP conduit definition.
=> Update IPMI handling to allow not configuring its network parameters.

deploy/compose/common.env
the matching change remove the path map in the compose file needs to be made
and the revproxy container needs to include the missing files.
=> revert setting tto include rebuild bower

core/rails/lib/api_helper.rb
this test was overly restrictive once we'd added the integer test
non-ID lookup names just need to be mixed number & letter, this test works for that.
=> improve regex test for IDs so that they can start with numbers

containers/cloudwrap/cloudwrap/api.rb, containers/cloudwrap/cloudwrap/common.rb, containers/cloudwrap/cloudwrap/waiter.rb, core/rails/app/models/aws_provider.rb, core/rails/config/locales/rebar/en.yml
Fog does NOT use VPC when creating VMs, you must supply subnet_id instead.
This changes the vpc_id in the AWS provider to use subnet_id instead.  
Tested this and it works.
Attention @galthaus
=> Fixes the AWS subnet create (was not actually VPC!)

containers/cloudwrap/cloudwrap/common.rb, core/rails/app/controllers/deployments_controller.rb
When creating a cloud workload, users want to be able to add their keys at the deployment.
This is needed for UX wizard changes in process.
=> allow deployment batch to add ssh keys

core/rails/app/models/network.rb
get the answer wrong if we have multiple admin networks.
lookup_network would not match when multiple networks specified.
=> If we find a network break out of all loops so that we don't

core/rails/app/models/node_role.rb, core/rails/db/migrate/20161013112500_add_pcms_soft.rb
relationship is a hard vs soft requirement.  Relationships that
come from a preceeds are soft and only for ordering, not directly
requirements.  All other reqs are assumed to be hard for the time
being.  This allows for delete to happen on things that have inject
preceeds.  For example, kubernetes minions should be deletable even
though the service role kubernetes "requires" them through a
preceeds.
=> This adds a flag (soft) to the pcms table to track if the

core/rails/app/models/barclamp.rb, core/rails/app/models/node_role.rb
was a member of a cluster.  One problem is that parent test vs
current cohort value was < and not <=.  We always want the new
node role's cohort to be at least one more that all of its parents.
This also updates the cohort on preceed additions to the graph.
If the new role is a parent to roles (because of preceeds), then
the cohort of the children need to be updated.
If the new role is a child a preceeds parent, then we make sure the
new cohort value for the new child is larger than the parent.
This seems to take care of most of the delete, remove, reset issues
I was seeing.  I'm not sure when this broke.
I've also update delete to only test for hard_children to match the rest of the delete children tests.
I've also added a update to role cohorts after barclamp import.  This seems to …
=> During node_role create cohort wasn't getting set unless the role

core/rails/app/controllers/nodes_controller.rb, core/rails/app/controllers/profiles_controller.rb, core/rails/app/models/attrib.rb, core/rails/app/models/node.rb, core/rails/app/models/node_role.rb, core/rails/app/models/profile.rb, core/rails/app/models/run.rb, core/rails/config/routes.rb, core/rails/db/migrate/20161021090000_add_profiles.rb, core/rails/db/seeds.rb, go/rebar-api/api/profile.go, go/rebar-api/datatypes/node.go, go/rebar-api/datatypes/profile.go, go/rebar-api/rebar/profile.go
This adds profiles as new top-level constructs in Digital Rebar.
A profile is a named mapping of attrib names to default values for those
attribs.  Unless overridden by the user (by setting attribs via the UI,
API, or CLI), attribs in a profile will take precedence over default
attribs from roles and deployment roles.
Nodes have been updated to contain a new top-level field called
'profiles', which should contain a list of profiles that apply to the
node.  Profiles apply to the node from the last to the first in the list
-- attrib values defined in a profile towards the fromt of the list get
merged in with attrib values from later in the list.  The logic is
similar to how attribs get smashed together -- the default provide the
basics, which the deploymentroles/noderoles/nodes can …
=> Add profile support to Rebar

core/barclamps/certexample.yml, core/rails/app/models/barclamp_cluster/make_ca.rb
since the root file label/name does not change, the system does not easily detect rotation.  
this adds an optional time field so that we can track rotations downstream.
=> include time field to help track root rotation

containers/provisioner/explode_iso.sh, go/provisioner-mgmt/bootenv.go, tools/windows/2012r2/build-2012r2-iso.ps1, tools/windows/2012r2/update-bootenv.ps1
Allow the provisioner to actually re-expand ISO files when a bootenv
update requires it, and update the windows powershell helper scripts
to generate more correct ISO images and upload them while updating the
appropriate boot environment
=> Fixup the provisioner and the windows 2012r2 helper scripts.

core/rails/app/controllers/application_controller.rb, core/rails/app/controllers/deployments_controller.rb, deploy/compose/config-dir/api/config/deployments/system-hw-roles.json
This will allow for profiles to override the values and allow
for persistant changes to defaults.
Create a workaround for the overloaded state variable in
deployments.  Patch operations would fail for all deployment
updates.  This removes state from the updatable variables.
USE COMMIT OR PROPOSE for those actions.
=> Make sure that the hardware roles are on the system deployment.

core/script/roles/bios-flash/01-flash.sh, core/script/roles/ipmi-flash/01-stub.sh
VALUES[$v] is the current firmware version, and $val is the version listed for the package.
=> Fix order of args to rev_lt for IPMI and BIOS flash scripts

core/rails/app/controllers/barclamps_controller.rb
this was added to support UX direct upload of barclamp buttons.
=> allow user to upload YAML barclamp instead of just JSON

containers/rebuild-containers, deploy/compose/config-dir/provisioner/bootenvs/redhat-7.0.json, deploy/compose/config-dir/provisioner/bootenvs/ubuntu-14.04.json, go/rebar-api/rebar/dhcp.go, go/rebar-dhcp/api.go, go/rebar-dhcp/data.go
This adds an unlease action for DHCP leases.  This can be helpful in debugging and resetting environments.
Fix provisioner bootenvs that were missing use-proxy as a required variable.
Update the build containers script to work with the MAC cross-compile requirements.
=> Dhcp unlease use proxy fixes build tweak

deploy/tasks/base-ubuntu1604.yml
Packet disables apparmor on their 1604 install and the tasks were failing.
=> bypass apprrmor if not enabled, needed for packet 1604

core/rails/app/models/barclamp_rebar/ansible_playbook_jig.rb
small usability tweak that improves readability for when files get long (which they do quickly)
=> allow playbook body to be array instead of long string

core/rails/app/models/deployment.rb
there is danger here BUT we need to move this to "buyer beware" because we want to be able to set system noderoles.
I will make matching changes to the UX with appropriate warnings.
reviewed by @galthaus
=> allow SYSTEM deployment to be proposed - needed for SSH key changes

containers/cloudwrap/cloudwrap/waiter.rb, core/rails/app/models/attrib.rb, deploy/compose/config-dir/provisioner/templates/centos-6.ks.tmpl, deploy/compose/config-dir/provisioner/templates/centos-7.ks.tmpl, deploy/compose/config-dir/provisioner/templates/net-post-install.sh.tmpl, deploy/compose/config-dir/provisioner/templates/sledgehammer-control.sh.tmpl
install so that rebar-access script can accurately manage them.
=> Add rebar-access content brackets around the ssh keys on

core/barclamps/ipmi.yml, core/script/roles/ipmi-flash/01-stub.sh
This adds a history variable that tracks updates over time.
This adds the wanted_version variable that can be latest or a specific
version.  If the value is latest, the code will walk from youngest to
oldest applying the updates in order until the version is the "latest"
in the list. If a specific version is specified, only that version will
be specified.  If the version is less than the current version, a force
variable is set and the scripts are updated to use it.
One design choice that was punted for now is if the wanted_version
is say 10, and the current is 6 and we know about 8 and 10, we will
only apply 10.  There are cases where this is desired and then there
are cases where we want to apply 8 and then 10.
=> IPMI wanted version

go/rebar-rev-proxy/proxy.go, go/rebar-rev-proxy/rebar-rev-proxy.go
UX optimization uses the "X-Return-Attributes" header which should have been included in the CORS list.  
This change adds the missing field and does some minor cleanups.
There is a matching pull for REMOVING CORS from the RAILS API because it was redundant with the Revproxy CORS; however, that required having the api/license call also use CORS in the proxy.go routine.
=> consolidate CORS headers, add missing headers, remove duplicates

core/barclamps/cluster.yml, core/bin/barclamp_import, core/rails/app/controllers/application_controller.rb, core/rails/app/controllers/docs_controller.rb, core/rails/app/controllers/users_controller.rb, core/rails/app/models/attrib.rb, core/rails/app/models/barclamp.rb, core/rails/config/application.rb, deploy/.gitignore, go/build-rebar.sh
Related to #150 
Remove the redundant CORS headers from the RAILS apps.  They were conflicting with the Revproxy in confusing ways.
To make attrib render correctly in the UX, we need to set the schema for all attribs.  That means that we CANNOT assume that schema = writable.  This change will allow us to set writable: false for some attribs.  
There are some other minor cleanups.
=> Remote Rails CORS & Allow Attrib Writable

core/rails/app/models/barclamp.rb, core/rails/app/models/barclamp_rebar/ansible_playbook_jig.rb, deploy/compose/docker-compose-common.yml
This removes the null variables from the TOP level of the passed attributes.  That allows those to be undefined instead of null.
In the future, it could be that we want to look at "required" flag instead of assuming all null are removed.
Also, prune relationships on barclamp import.
=> Ansible does not like passing NULL variables

core/rails/app/models/attrib.rb
They will get poked when the deployment or node are committed.
=> Node roles in the proposed state should not be poked.

core/rails/app/controllers/deployments_controller.rb, core/rails/app/models/barclamp_rebar/ansible_playbook_jig.rb, core/rails/app/models/deployment_role.rb, core/rails/app/models/jig.rb, core/rails/app/models/node_role.rb, core/rails/config/routes.rb
Primarily this adds a new view to support the UX/VX optimization.  The new view /api/status/matrix is NOT part of the API so it does not have a contract.  The is designed strictly to improve render for the Matrix view so that we do not have to pre-fetch so much data before rendering.
Also, minor adds to the node_roles and deployment_roles to prevent extra look ups in roles by adding role name and icon.  These fields were prefixed with _ to show they are not part of the model.  We may want to use that pattern more broadly when we denormalize the API model.  The denormalization is useful.
Also included attempt to fix #169 - needs more testing but not harmful.
=> Matrix View, view tweaks for UX

core/barclamps/bios.yml, core/rails/app/models/barclamp_bios/discover.rb
Using structurematch was being too permissive and picking incompatible
BIOS config sets for the R630 and a different SuperMicro box.
Switched the code over to using straight regex matches for all attrib
matching when picking the right BIOS config set for a node.
=> Make bios config set matching more strict.

core/barclamps/chef.yml, core/script/roles/chef-client/01-install-client.sh
This also upgrades the version of Chef we install to 12.18.31,
and the code for the chef-client role allows for the Chef
package to be cached on the provisioner.  This works for the Chef
client because the deb/rpm/whatever file are all omnibus installs
under the hood.
=> Allow for configurable chef-client install locations.

core/rails/app/controllers/network_ranges_controller.rb
working on allowing users to edit DHCP leases requires that the API can update the values
=> Allow editing the lease times

core/barclamps/bios.yml
It used to live on the bios-dell-rseries-configure role, which was the
wrong place.  It now lives on its own role, and the role dependency
graph has been updated accordingly.
=> Shift the location of the bios-configuration attrib.

core/rails/app/models/barclamp_bios/supermicro_configure.rb
It was preventing the supermicro-configure role from extracting the
sum binary in the on_proposed hook.
=> Fix stupid single-char typo in supermicro_configure

deploy/tasks/compose.yml
From Gitter: 
Greg O @gregoryo2008_twitter 02:20
Okay I'm giving Rebar a go, and from the quickstart initial script I get errors because of Centos versions. To fix, I manually changed tasks/compose.yml to get 7.3.1611 instead of 7.2.1511 (since it's now gone), and updated the checksum.
=> add 7.3.1611 centos

containers/rebar-api/entrypoint.d/07-explode-supermicro-update-manager.sh, core/rails/app/models/barclamp_bios/supermicro.rb, core/rails/app/models/barclamp_bios/supermicro_configure.rb, deploy/.gitignore, deploy/compose/docker-compose-common.yml
Previous methods of adding external tools for use by the containers was
rather ad-hoc.  This standardizes it that all tool distribution
files (.zip, .tar.gz, etc) should be placed in
deploy/compose/config-dir/tools, and that any tool binaries (sum, etc.)
should be placed in deploy/compose/config-dir/tools/bin.
deploy/compose/config-dir/tools will be mapped into the containers at
/opt/tools.
The primary user of this functionality is Supermicro remote BIOS
configuration support
=> Review only -- Add extensible support using external tools

deploy/workloads/cluster/deploy-001.json, deploy/workloads/cluster/deploy-002.json, deploy/workloads/multideploy.sh
providers were not working correctly for fresh installs.
added tenant detection and addition
that required replacing tenant with tenant_id (we do not look up tenant in deployment, ID is required)
At this point, the script will 
1) add provider from ~/.dr_info (if missing from system)
2) add tenant if included in file and new
3) replace tenant with tenant_id
4) create the deployment
DOES NOT WORK if the deployment exists.  In that case, use --destroy and retry!
=> add tenant support for multideploy, fix provider bug

go/rebar-api/datatypes/node.go
This makes it easier to allow things that jsut want the hostname part of
the FQDN to be written without excessive juggling during template expansion.
=> Add ShortName helper to the Node api datatype.

deploy/compose/config-dir/provisioner/bootenvs/ubuntu-16.04.json, deploy/tasks/compose.yml, go/provisioner-mgmt/bootenvs/ubuntu-16.04.json
16.04.2 was released on February 17th, 2017
=> Update URL's for Ubuntu 16.04 to reference 16.04.2

core/rails/app/models/barclamp.rb, go/rule-engine/engine/action.go
This allows the rule engine and the classifier to set/append/remove
profiles from nodes.  I also added a convienence helper in the barclamp
import code to allow importing profiles.
=> Add profile ops to the rule-engine core

deploy/digitalrebar.yml, deploy/tasks/compose.yml
This change reduces the number of places where we have to track the URLs for ISOs since they change all the time.
We will still need to update for major version changes in the digitalrebar.yml
=> Pull ISO information from Bootenv instead of hardcoded 

core/barclamps/bios.yml
This allows the bios-config-sets attrib to be included in a profile,
making it easier to define custom BIOS settings that should be applied
across a block of systems.
=> Add schema to bios-config-sets

deploy/tasks/compose.yml
this only applies when run from a remote system, but avoids an unneeded copy in those cases.
=> for cloud type, we don't need RAID or BIOS files copied

containers/cloudwrap/cloudwrap/openstack.rb, core/rails/app/models/open_stack_provider.rb
This fixes the cloudwrap back end so that we can take new parameters without cloudwrap changes.
It will require the cloudwrap to be rebuilt.  The new params will be surfaced in the UI because of the model change.
=> issue #237 - needed to add ad-hoc items to openstack command line

deploy/tasks/compose.yml
So, this is a minor change but it's to prevent this:
=> Add trailing slashes to correctly sync RAID tools dir

core/chef/cookbooks/network/recipes/default.rb, core/rails/app/models/network.rb, core/script/roles/chef-client/01-install-client.sh
First, off-line mode works until you need cstruct gem.  We don't have
a way to cache it.  We do now.  It has been moved to the chef client
role since it already has that style and information.  The network
role doesn't try to install cstruct now.  It assumes chef-client role
put it in place.
Second, Add a new conduit option.  raw:interface
Instead of using the conduit maps to resolve the interface.  This allows
for a raw specification of the interface name, e.g. raw:ens4.
This will put the ip address assigned for this network on that
interface.  The raw: syntax functions with the bond and bridge code as
well.
=> Address a couple of issues that are network related.

core/rails/app/controllers/nodes_controller.rb
This allows for DRP to create nodes with matching UUIDs as its Machines.
=> Allow uuid to be set on node create.

core/rails/app/controllers/deployments_controller.rb, core/rails/app/models/barclamp_flash/discover.rb, core/rails/app/models/deployment.rb, core/rails/app/models/deployment_role.rb, core/rails/app/models/node.rb, core/rails/app/models/role.rb, core/rails/db/migrate/20170609084000_add_profiles_to_deployments.rb, go/rebar-api/datatypes/deployment.go
The deployments model gains a profiles column along with equivalent functionality.
Deployment profiles have a higher precedence than defaults, and a lower precedence than
values set via a node-specific profiles.  Values in deployment profiles will be looked
up in the context of the node's current deployment, and values set via parent deployments
are also mixed in.
=> Add profiles support for deployments as well as nodes

core/barclamps/provisioner.yml, core/rails/app/models/barclamp_provisioner/os_install.rb
We stop setting provisioner-target_os on the deployment role at bind
time, as that prevents us from picking the value up from a profile set
in a deployment.
Instead, set it on the node if and only if the node is not already
getting a value from somewhere else.
=> Shift around where we set provisioner-target_os.

core/rails/app/controllers/deployments_controller.rb
The service roles (which are deployment roles) were showing up in both places.  This small change removes them from the deployment roles list so the UX renders correctly.
NOTE: There is still a bug in the UX where the deployment_role is not linked correctly.
=> Duplicated service roles in deploy matrix

containers/provisioner/start-up.sh, core/rails/app/controllers/networks_controller.rb, core/rails/app/models/network_allocation.rb, core/rails/app/models/network_range.rb, deploy/compose/config-dir/api/config/networks/the_admin.json.forwarder
This change allows Rebar to hand out both short-term leases and bind
reservations from the same network range.  The use case is where Rebar
is managing DHCP for a subnet that is expected to be completly
populated (hence we cannot set aside a pool of addresses for initial
system discovery), and so we will need to arrange to allocate the
addresses a system used for initial discovery to that system on a
long-term basis.
Sledgehammer has also been updated to pass all of the MAC addresses
for discovered Ethernet devices at node create time, instead of just
the MAC that the system happened to boot from.  This gets rid of
spurious node creation when (due to forces beyond our control) the
system PXE boots from a different nic during the provision process.
=> Allow leases and bindings in the same nework range.

deploy/compose/config-dir/provisioner/bootenvs/ubuntu-16.04.json, go/provisioner-mgmt/bootenvs/ubuntu-16.04.json
Canonical in their infinite wisdom seems to only ship the most recent
ISOs at their well known URLs and thus on mirrors now.
Potential fix for #306 
It's also possible you may want to use the official distribution URL of http://releases.ubuntu.com/16.04.3/ubuntu-16.04.3-server-amd64.iso to take some load off mirrors.kernel.org
=> Bump Ubuntu releases to 16.04.3

core/rails/app/models/secure_shell_hammer.rb, deploy/compose/config-dir/provisioner/templates/rebar-join.sh.tmpl
Update the rebar_join script and the SSH jig reboot command to
leave node aliveness alone if the node is not available.
This leaves the noderole states alone when we do not want them to change
across a reboot.
=> Do not change node aliveness when it is not available.
